name: Publish to npm
description: Generate and publish npm package to npm and GitHub Packages
inputs:
  github-token:
    description: GitHub token
    required: true
  npm-token:
    description: npm token
    required: true
runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - run: |
        deno install -qAn vr https://deno.land/x/velociraptor@1.5.0/cli.ts
        vr npm
      shell: bash

    - uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org/
    - run: npm publish
      working-directory: ./npm
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - uses: actions/setup-node@v4
      with:
        registry-url: https://npm.pkg.github.com/
    - run: npm publish
      working-directory: ./npm
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-token }}
