name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          include-v-in-tag: false
          extra-files: |
            README.md
            build_npm.ts

      - if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/npm-publish
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
