name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install Velociraptor
        run: deno install -qAn vr https://deno.land/x/velociraptor@1.5.0/cli.ts

      - name: Format
        run: vr fmt
      - name: Lint
        run: vr lint
      - name: Test
        run: vr test:ci

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
          fail_ci_if_error: true
